support_measures:
  - государственная программа развития сельского хозяйства
  - государственная поддержка АПК
  - субсидии сельское хозяйство
  - Финансирование АПК
  - мелиорац
  - семеноводств
  - агрострахован

subsidy_terms:
  - возмещение затрат сельхозпроизводителям
  - возмещение части затрат сельхозтоваропроизводителям
  - прямые субсидии сельхозпроизводителям
  - косвенные субсидии сельхозпроизводителям
  - субсидии на создание и модернизацию объектов по переработке сельскохозяйственной продукции

credit_terms:
  - льготные кредиты в АПК
  - предоставление и распределение субсидий на уплату процентов по инвестиционным кредитам в агропромышленном комплексе

export_support:
  - Поддержка экспорта АПК
  - экспортная пошлина
  - компенсация транспортировки
  - квота на вывоз
  - вывозная квота

livestock_support:
  - субсидии на разведение крупного рогатого скота молочного направления
  - Государственная поддержка молочного животноводства

grain_support:
  - финансовое обеспечение возмещение производителям зерновых культур части затрат на производство и реализацию зерновых культур
  - Поддержка элитного семеноводства

regulatory_change:
  - Постановление 1528 изменения
  - порядок предоставления
  - предоставление и распределение субсидий из федерального бюджета бюджетам субъектов Российской Федерации на АПК

public_discussion:
  - публичное обсуждение
  - публичные консультации
  - оценка регулирующего воздействия
